import type { SiteLocale } from "@/lib/site-locale";

type PageViewMessageKey =
  | "consent"
  | "fields"
  | "excluded"
  | "retention"
  | "session"
  | "history"
  | "disable"
  | "disableError"
  | "disabledSuccess";

type PageViewMessages = Record<PageViewMessageKey, string>;

// Keep the consent disclosure understandable in every supported locale
// without sending legal or privacy copy to a paid translation provider.
const PAGE_VIEW_MESSAGES = new Map<SiteLocale, PageViewMessages>([
  ["en", {
    consent: "Disabled by default; collection starts only after explicit approval by a project administrator.",
    fields: "Only the URL path without query parameters or fragments, target language, timestamp, and random one-time event ID are stored.",
    excluded: "Visitor IP addresses, browser identifiers, referrers, cookies, fingerprints, and persistent visitor identifiers are not stored.",
    retention: "Events are automatically deleted after 90 days; obvious bots and duplicate reports are excluded.",
    session: "A short-lived entry in the current browser tab prevents duplicate reports.",
    history: "Historical translation requests are never counted as visitor page views.",
    disable: "Disable tracking",
    disableError: "Page-view tracking could not be disabled.",
    disabledSuccess: "Page-view tracking disabled.",
  }],
  ["de", {
    consent: "Standardmäßig deaktiviert; die Erfassung beginnt erst nach ausdrücklicher Zustimmung einer Projektadministration.",
    fields: "Gespeichert werden ausschließlich der URL-Pfad ohne Anfrageparameter oder Fragmente, die Zielsprache, der Zeitpunkt und eine zufällige einmalige Ereigniskennung.",
    excluded: "IP-Adressen, Browserkennungen, Referrer, Cookies, Fingerabdrücke und dauerhafte Besucherkennungen werden nicht gespeichert.",
    retention: "Ereignisse werden nach 90 Tagen automatisch gelöscht; offensichtliche Bots und doppelte Meldungen werden ausgeschlossen.",
    session: "Ein kurzlebiger Eintrag im aktuellen Browser-Tab verhindert doppelte Meldungen.",
    history: "Bisherige Übersetzungsanfragen werden niemals als Seitenaufrufe gezählt.",
    disable: "Erfassung deaktivieren",
    disableError: "Die Erfassung von Seitenaufrufen konnte nicht deaktiviert werden.",
    disabledSuccess: "Die Erfassung von Seitenaufrufen wurde deaktiviert.",
  }],
  ["bg", {
    consent: "Изключено по подразбиране; събирането започва само след изрично съгласие на администратор на проекта.",
    fields: "Запазват се само URL пътят без параметри или фрагменти, целевият език, часът и случаен еднократен идентификатор.",
    excluded: "IP адреси, идентификатори на браузъра, препращащи адреси, бисквитки, отпечатъци и постоянни идентификатори не се запазват.",
    retention: "Събитията се изтриват автоматично след 90 дни; явните ботове и дублираните отчети се изключват.",
    session: "Краткотраен запис в текущия раздел на браузъра предотвратява дублирани отчети.",
    history: "Предишните заявки за превод никога не се отчитат като посещения на страници.",
    disable: "Изключване на отчитането",
    disableError: "Отчитането на посещенията не можа да бъде изключено.",
    disabledSuccess: "Отчитането на посещенията е изключено.",
  }],
  ["hr", {
    consent: "Zadano je isključeno; prikupljanje počinje tek nakon izričitog pristanka administratora projekta.",
    fields: "Pohranjuju se samo URL putanja bez parametara ili fragmenata, ciljni jezik, vrijeme i nasumični jednokratni identifikator događaja.",
    excluded: "IP adrese, identifikatori preglednika, refereri, kolačići, otisci i trajni identifikatori posjetitelja ne pohranjuju se.",
    retention: "Događaji se automatski brišu nakon 90 dana; očiti botovi i dvostruke prijave se isključuju.",
    session: "Kratkotrajni zapis u trenutačnoj kartici preglednika sprječava dvostruke prijave.",
    history: "Prethodni zahtjevi za prijevod nikada se ne računaju kao pregledi stranica.",
    disable: "Isključi praćenje",
    disableError: "Praćenje pregleda stranica nije moguće isključiti.",
    disabledSuccess: "Praćenje pregleda stranica je isključeno.",
  }],
  ["cs", {
    consent: "Ve výchozím nastavení je vypnuto; sběr začíná až po výslovném souhlasu správce projektu.",
    fields: "Ukládá se pouze cesta URL bez parametrů nebo fragmentů, cílový jazyk, čas a náhodný jednorázový identifikátor události.",
    excluded: "IP adresy, identifikátory prohlížeče, odkazující stránky, soubory cookie, otisky ani trvalé identifikátory návštěvníků se neukládají.",
    retention: "Události se automaticky mažou po 90 dnech; zjevní roboti a duplicitní hlášení jsou vyloučeni.",
    session: "Krátkodobý záznam v aktuální kartě prohlížeče zabraňuje duplicitním hlášením.",
    history: "Dřívější požadavky na překlad se nikdy nezapočítávají jako zobrazení stránek.",
    disable: "Vypnout sledování",
    disableError: "Sledování zobrazení stránek se nepodařilo vypnout.",
    disabledSuccess: "Sledování zobrazení stránek bylo vypnuto.",
  }],
  ["da", {
    consent: "Deaktiveret som standard; indsamling begynder først efter udtrykkeligt samtykke fra en projektadministrator.",
    fields: "Kun URL-stien uden forespørgselsparametre eller fragmenter, målsprog, tidspunkt og et tilfældigt engangs-id gemmes.",
    excluded: "Besøgendes IP-adresser, browseridentifikatorer, henvisninger, cookies, fingeraftryk og vedvarende identifikatorer gemmes ikke.",
    retention: "Hændelser slettes automatisk efter 90 dage; åbenlyse bots og dobbelte rapporter udelukkes.",
    session: "En kortvarig post i den aktuelle browserfane forhindrer dobbelte rapporter.",
    history: "Tidligere oversættelsesanmodninger tælles aldrig som sidevisninger.",
    disable: "Deaktiver registrering",
    disableError: "Registrering af sidevisninger kunne ikke deaktiveres.",
    disabledSuccess: "Registrering af sidevisninger er deaktiveret.",
  }],
  ["nl", {
    consent: "Standaard uitgeschakeld; verzameling begint pas na uitdrukkelijke toestemming van een projectbeheerder.",
    fields: "Alleen het URL-pad zonder queryparameters of fragmenten, de doeltaal, het tijdstip en een willekeurige eenmalige gebeurtenis-ID worden opgeslagen.",
    excluded: "IP-adressen, browseridentificatoren, verwijzers, cookies, vingerafdrukken en blijvende bezoekersidentificatoren worden niet opgeslagen.",
    retention: "Gebeurtenissen worden na 90 dagen automatisch verwijderd; duidelijke bots en dubbele meldingen worden uitgesloten.",
    session: "Een tijdelijke vermelding in het huidige browsertabblad voorkomt dubbele meldingen.",
    history: "Eerdere vertaalaanvragen worden nooit meegeteld als paginaweergaven.",
    disable: "Registratie uitschakelen",
    disableError: "Registratie van paginaweergaven kon niet worden uitgeschakeld.",
    disabledSuccess: "Registratie van paginaweergaven is uitgeschakeld.",
  }],
  ["et", {
    consent: "Vaikimisi välja lülitatud; andmete kogumine algab alles projekti administraatori selgesõnalisel nõusolekul.",
    fields: "Salvestatakse ainult URL-i tee ilma päringuparameetrite või fragmentideta, sihtkeel, aeg ja juhuslik ühekordne sündmuse tunnus.",
    excluded: "Külastajate IP-aadresse, brauseritunnuseid, viitajaid, küpsiseid, sõrmejälgi ega püsivaid külastajatunnuseid ei salvestata.",
    retention: "Sündmused kustutatakse automaatselt 90 päeva pärast; ilmsed robotid ja topeltteated jäetakse välja.",
    session: "Praegusel brauserivahekaardil olev lühiajaline kirje takistab topeltteateid.",
    history: "Varasemaid tõlkepäringuid ei arvestata kunagi lehevaatamistena.",
    disable: "Lülita jälgimine välja",
    disableError: "Lehevaatamiste jälgimist ei õnnestunud välja lülitada.",
    disabledSuccess: "Lehevaatamiste jälgimine on välja lülitatud.",
  }],
  ["fi", {
    consent: "Oletusarvoisesti pois käytöstä; tietojen keruu alkaa vasta projektin ylläpitäjän nimenomaisella suostumuksella.",
    fields: "Tallennetaan vain URL-polku ilman kyselyparametreja tai fragmentteja, kohdekieli, aikaleima ja satunnainen kertakäyttöinen tapahtumatunnus.",
    excluded: "Kävijöiden IP-osoitteita, selaintunnisteita, viittaajia, evästeitä, sormenjälkiä tai pysyviä kävijätunnisteita ei tallenneta.",
    retention: "Tapahtumat poistetaan automaattisesti 90 päivän kuluttua; ilmeiset botit ja kaksoisilmoitukset suljetaan pois.",
    session: "Nykyisen selainvälilehden lyhytaikainen merkintä estää kaksoisilmoitukset.",
    history: "Aiemmat käännöspyynnöt eivät koskaan lisää sivukatselujen määrää.",
    disable: "Poista seuranta käytöstä",
    disableError: "Sivukatselujen seurantaa ei voitu poistaa käytöstä.",
    disabledSuccess: "Sivukatselujen seuranta on poistettu käytöstä.",
  }],
  ["fr", {
    consent: "Désactivé par défaut ; la collecte commence uniquement après le consentement explicite d’un administrateur du projet.",
    fields: "Seuls le chemin URL sans paramètres ni fragments, la langue cible, l’horodatage et un identifiant aléatoire à usage unique sont enregistrés.",
    excluded: "Les adresses IP, identifiants de navigateur, référents, cookies, empreintes et identifiants persistants des visiteurs ne sont pas enregistrés.",
    retention: "Les événements sont automatiquement supprimés après 90 jours ; les robots évidents et les doublons sont exclus.",
    session: "Une entrée temporaire dans l’onglet actuel du navigateur empêche les signalements en double.",
    history: "Les demandes de traduction antérieures ne sont jamais comptabilisées comme des pages vues.",
    disable: "Désactiver le suivi",
    disableError: "Le suivi des pages vues n’a pas pu être désactivé.",
    disabledSuccess: "Le suivi des pages vues est désactivé.",
  }],
  ["el", {
    consent: "Απενεργοποιημένο από προεπιλογή· η συλλογή ξεκινά μόνο μετά από ρητή συγκατάθεση διαχειριστή του έργου.",
    fields: "Αποθηκεύονται μόνο η διαδρομή URL χωρίς παραμέτρους ή τμήματα, η γλώσσα προορισμού, η χρονική σήμανση και ένα τυχαίο αναγνωριστικό μίας χρήσης.",
    excluded: "Δεν αποθηκεύονται διευθύνσεις IP, αναγνωριστικά προγράμματος περιήγησης, παραπομπές, cookies, αποτυπώματα ή μόνιμα αναγνωριστικά επισκεπτών.",
    retention: "Τα συμβάντα διαγράφονται αυτόματα μετά από 90 ημέρες· εξαιρούνται προφανή bot και διπλές αναφορές.",
    session: "Μια προσωρινή εγγραφή στην τρέχουσα καρτέλα αποτρέπει τις διπλές αναφορές.",
    history: "Τα προηγούμενα αιτήματα μετάφρασης δεν υπολογίζονται ποτέ ως προβολές σελίδων.",
    disable: "Απενεργοποίηση καταγραφής",
    disableError: "Δεν ήταν δυνατή η απενεργοποίηση της καταγραφής προβολών.",
    disabledSuccess: "Η καταγραφή προβολών σελίδων απενεργοποιήθηκε.",
  }],
  ["hu", {
    consent: "Alapértelmezés szerint ki van kapcsolva; az adatgyűjtés csak a projekt rendszergazdájának kifejezett hozzájárulásával indul.",
    fields: "Csak a lekérdezési paraméterek és töredékek nélküli URL-útvonal, a célnyelv, az időbélyeg és egy véletlenszerű egyszer használatos eseményazonosító tárolódik.",
    excluded: "A látogatók IP-címei, böngészőazonosítói, hivatkozói, cookie-jai, ujjlenyomatai és állandó azonosítói nem kerülnek tárolásra.",
    retention: "Az események 90 nap után automatikusan törlődnek; a nyilvánvaló robotok és az ismétlődő jelentések kizárásra kerülnek.",
    session: "Az aktuális böngészőlapon lévő rövid élettartamú bejegyzés megakadályozza az ismétlődő jelentéseket.",
    history: "A korábbi fordítási kérelmek soha nem számítanak oldalmegtekintésnek.",
    disable: "Követés kikapcsolása",
    disableError: "Az oldalmegtekintések követését nem sikerült kikapcsolni.",
    disabledSuccess: "Az oldalmegtekintések követése kikapcsolva.",
  }],
  ["ga", {
    consent: "Díchumasaithe de réir réamhshocraithe; ní thosaíonn bailiú ach le toiliú sainráite ó riarthóir tionscadail.",
    fields: "Ní stóráiltear ach an chonair URL gan pharaiméadair ná blúirí, an sprioctheanga, an t-am agus aitheantóir randamach aonúsáide.",
    excluded: "Ní stóráiltear seoltaí IP, aitheantóirí brabhsálaí, atreoróirí, fianáin, méarloirg ná aitheantóirí buana cuairteoirí.",
    retention: "Scriostar imeachtaí go huathoibríoch tar éis 90 lá; fágtar róbait shoiléire agus tuairiscí dúblacha ar lár.",
    session: "Cuireann iontráil ghearrshaolach sa chluaisín brabhsálaí reatha cosc ar thuairiscí dúblacha.",
    history: "Ní áirítear iarratais aistriúcháin roimhe seo mar amhairc leathanaigh.",
    disable: "Díchumasaigh rianú",
    disableError: "Níorbh fhéidir rianú amharc leathanaigh a dhíchumasú.",
    disabledSuccess: "Tá rianú amharc leathanaigh díchumasaithe.",
  }],
  ["it", {
    consent: "Disattivato per impostazione predefinita; la raccolta inizia solo dopo il consenso esplicito di un amministratore del progetto.",
    fields: "Vengono memorizzati solo il percorso URL senza parametri o frammenti, la lingua di destinazione, l’orario e un identificatore casuale monouso.",
    excluded: "Indirizzi IP, identificatori del browser, referer, cookie, impronte digitali e identificatori persistenti dei visitatori non vengono memorizzati.",
    retention: "Gli eventi vengono eliminati automaticamente dopo 90 giorni; bot evidenti e segnalazioni duplicate sono esclusi.",
    session: "Una voce temporanea nella scheda corrente del browser impedisce segnalazioni duplicate.",
    history: "Le richieste di traduzione precedenti non vengono mai conteggiate come visualizzazioni di pagina.",
    disable: "Disattiva il monitoraggio",
    disableError: "Non è stato possibile disattivare il monitoraggio delle visualizzazioni.",
    disabledSuccess: "Monitoraggio delle visualizzazioni disattivato.",
  }],
  ["lv", {
    consent: "Pēc noklusējuma izslēgts; datu vākšana sākas tikai pēc projekta administratora nepārprotamas piekrišanas.",
    fields: "Tiek saglabāts tikai URL ceļš bez vaicājuma parametriem vai fragmentiem, mērķa valoda, laiks un nejaušs vienreizējs notikuma identifikators.",
    excluded: "Apmeklētāju IP adreses, pārlūkprogrammas identifikatori, novirzītāji, sīkdatnes, nospiedumi un pastāvīgi identifikatori netiek saglabāti.",
    retention: "Notikumi tiek automātiski dzēsti pēc 90 dienām; acīmredzami roboti un atkārtoti ziņojumi tiek izslēgti.",
    session: "Īslaicīgs ieraksts pašreizējā pārlūkprogrammas cilnē novērš atkārtotus ziņojumus.",
    history: "Iepriekšējie tulkošanas pieprasījumi nekad netiek uzskaitīti kā lapu skatījumi.",
    disable: "Izslēgt uzskaiti",
    disableError: "Lapu skatījumu uzskaiti neizdevās izslēgt.",
    disabledSuccess: "Lapu skatījumu uzskaite ir izslēgta.",
  }],
  ["lt", {
    consent: "Pagal numatytuosius nustatymus išjungta; duomenys renkami tik gavus aiškų projekto administratoriaus sutikimą.",
    fields: "Saugomas tik URL kelias be užklausos parametrų ar fragmentų, tikslinė kalba, laikas ir atsitiktinis vienkartinis įvykio identifikatorius.",
    excluded: "Lankytojų IP adresai, naršyklės identifikatoriai, nukreipimo šaltiniai, slapukai, pirštų atspaudai ir nuolatiniai identifikatoriai nesaugomi.",
    retention: "Įvykiai automatiškai ištrinami po 90 dienų; akivaizdūs robotai ir pasikartojantys pranešimai neįtraukiami.",
    session: "Trumpalaikis įrašas dabartiniame naršyklės skirtuke apsaugo nuo pasikartojančių pranešimų.",
    history: "Ankstesnės vertimo užklausos niekada neskaičiuojamos kaip puslapių peržiūros.",
    disable: "Išjungti stebėjimą",
    disableError: "Nepavyko išjungti puslapių peržiūrų stebėjimo.",
    disabledSuccess: "Puslapių peržiūrų stebėjimas išjungtas.",
  }],
  ["mt", {
    consent: "Diżattivat b’mod awtomatiku; il-ġbir jibda biss wara kunsens espliċitu minn amministratur tal-proġett.",
    fields: "Jinħażnu biss il-mogħdija tal-URL mingħajr parametri jew frammenti, il-lingwa fil-mira, il-ħin u identifikatur każwali ta’ użu wieħed.",
    excluded: "Indirizzi IP, identifikaturi tal-browser, referenzi, cookies, marki tas-swaba’ u identifikaturi permanenti tal-viżitaturi ma jinħażnux.",
    retention: "L-avvenimenti jitħassru awtomatikament wara 90 jum; bots ovvji u rapporti doppji jiġu esklużi.",
    session: "Entrata temporanja fit-tab attwali tal-browser tipprevjeni rapporti doppji.",
    history: "Talbiet preċedenti għat-traduzzjoni qatt ma jingħaddu bħala żjarat tal-paġna.",
    disable: "Itfi t-traċċar",
    disableError: "It-traċċar taż-żjarat tal-paġna ma setax jintefa.",
    disabledSuccess: "It-traċċar taż-żjarat tal-paġna ntefa.",
  }],
  ["pl", {
    consent: "Domyślnie wyłączone; zbieranie danych rozpoczyna się dopiero po wyraźnej zgodzie administratora projektu.",
    fields: "Zapisywane są wyłącznie ścieżka URL bez parametrów i fragmentów, język docelowy, czas oraz losowy jednorazowy identyfikator zdarzenia.",
    excluded: "Adresy IP, identyfikatory przeglądarki, strony odsyłające, pliki cookie, odciski cyfrowe i trwałe identyfikatory odwiedzających nie są zapisywane.",
    retention: "Zdarzenia są automatycznie usuwane po 90 dniach; oczywiste boty i zduplikowane zgłoszenia są wykluczane.",
    session: "Krótkotrwały wpis w bieżącej karcie przeglądarki zapobiega zduplikowanym zgłoszeniom.",
    history: "Wcześniejsze żądania tłumaczenia nigdy nie są liczone jako odsłony strony.",
    disable: "Wyłącz śledzenie",
    disableError: "Nie udało się wyłączyć śledzenia odsłon strony.",
    disabledSuccess: "Śledzenie odsłon strony zostało wyłączone.",
  }],
  ["pt", {
    consent: "Desativado por predefinição; a recolha começa apenas após o consentimento explícito de um administrador do projeto.",
    fields: "São guardados apenas o caminho do URL sem parâmetros ou fragmentos, o idioma de destino, a data e um identificador aleatório de utilização única.",
    excluded: "Endereços IP, identificadores do navegador, referências, cookies, impressões digitais e identificadores persistentes dos visitantes não são guardados.",
    retention: "Os eventos são eliminados automaticamente após 90 dias; bots evidentes e comunicações duplicadas são excluídos.",
    session: "Uma entrada temporária no separador atual do navegador evita comunicações duplicadas.",
    history: "Os pedidos de tradução anteriores nunca são contabilizados como visualizações de página.",
    disable: "Desativar registo",
    disableError: "Não foi possível desativar o registo de visualizações.",
    disabledSuccess: "O registo de visualizações foi desativado.",
  }],
  ["ro", {
    consent: "Dezactivat implicit; colectarea începe numai după acordul explicit al unui administrator de proiect.",
    fields: "Sunt stocate doar calea URL fără parametri sau fragmente, limba țintă, momentul și un identificator aleatoriu de unică folosință.",
    excluded: "Adresele IP, identificatorii browserului, sursele de referință, modulele cookie, amprentele și identificatorii permanenți ai vizitatorilor nu sunt stocate.",
    retention: "Evenimentele sunt șterse automat după 90 de zile; roboții evidenți și raportările duplicate sunt excluse.",
    session: "O înregistrare temporară în fila curentă a browserului previne raportările duplicate.",
    history: "Cererile de traducere anterioare nu sunt niciodată numărate ca vizualizări de pagină.",
    disable: "Dezactivează urmărirea",
    disableError: "Urmărirea vizualizărilor de pagină nu a putut fi dezactivată.",
    disabledSuccess: "Urmărirea vizualizărilor de pagină a fost dezactivată.",
  }],
  ["sk", {
    consent: "Predvolene vypnuté; zhromažďovanie začína až po výslovnom súhlase správcu projektu.",
    fields: "Ukladá sa iba cesta URL bez parametrov alebo fragmentov, cieľový jazyk, čas a náhodný jednorazový identifikátor udalosti.",
    excluded: "IP adresy, identifikátory prehliadača, odkazujúce stránky, súbory cookie, odtlačky ani trvalé identifikátory návštevníkov sa neukladajú.",
    retention: "Udalosti sa automaticky vymažú po 90 dňoch; zjavné roboty a duplicitné hlásenia sa vylúčia.",
    session: "Krátkodobý záznam v aktuálnej karte prehliadača zabraňuje duplicitným hláseniam.",
    history: "Predchádzajúce požiadavky na preklad sa nikdy nezapočítavajú ako zobrazenia stránok.",
    disable: "Vypnúť sledovanie",
    disableError: "Sledovanie zobrazení stránok sa nepodarilo vypnúť.",
    disabledSuccess: "Sledovanie zobrazení stránok bolo vypnuté.",
  }],
  ["sl", {
    consent: "Privzeto izklopljeno; zbiranje se začne šele po izrecnem soglasju skrbnika projekta.",
    fields: "Shranjujejo se samo pot URL brez parametrov ali fragmentov, ciljni jezik, čas in naključni enkratni identifikator dogodka.",
    excluded: "Naslovi IP, identifikatorji brskalnika, napotitelji, piškotki, prstni odtisi in trajni identifikatorji obiskovalcev se ne shranjujejo.",
    retention: "Dogodki se samodejno izbrišejo po 90 dneh; očitni roboti in podvojena poročila so izključeni.",
    session: "Kratkotrajen zapis v trenutnem zavihku brskalnika preprečuje podvojena poročila.",
    history: "Prejšnje zahteve za prevod se nikoli ne štejejo kot ogledi strani.",
    disable: "Izklopi beleženje",
    disableError: "Beleženja ogledov strani ni bilo mogoče izklopiti.",
    disabledSuccess: "Beleženje ogledov strani je izklopljeno.",
  }],
  ["es", {
    consent: "Desactivado de forma predeterminada; la recopilación comienza únicamente tras el consentimiento expreso de un administrador del proyecto.",
    fields: "Solo se guardan la ruta URL sin parámetros ni fragmentos, el idioma de destino, la fecha y un identificador aleatorio de un solo uso.",
    excluded: "No se guardan direcciones IP, identificadores del navegador, referencias, cookies, huellas digitales ni identificadores persistentes de visitantes.",
    retention: "Los eventos se eliminan automáticamente después de 90 días; se excluyen los bots evidentes y los informes duplicados.",
    session: "Una entrada temporal en la pestaña actual del navegador evita informes duplicados.",
    history: "Las solicitudes de traducción anteriores nunca se contabilizan como visitas a páginas.",
    disable: "Desactivar el seguimiento",
    disableError: "No se pudo desactivar el seguimiento de visitas a páginas.",
    disabledSuccess: "El seguimiento de visitas a páginas está desactivado.",
  }],
  ["sv", {
    consent: "Avstängt som standard; insamling börjar först efter uttryckligt samtycke från en projektadministratör.",
    fields: "Endast URL-sökvägen utan frågeparametrar eller fragment, målspråk, tidpunkt och ett slumpmässigt engångs-id sparas.",
    excluded: "Besökares IP-adresser, webbläsaridentifierare, hänvisningar, kakor, fingeravtryck och beständiga besöksidentifierare sparas inte.",
    retention: "Händelser raderas automatiskt efter 90 dagar; uppenbara botar och dubbla rapporter utesluts.",
    session: "En kortvarig post i den aktuella webbläsarfliken förhindrar dubbla rapporter.",
    history: "Tidigare översättningsförfrågningar räknas aldrig som sidvisningar.",
    disable: "Stäng av registrering",
    disableError: "Registrering av sidvisningar kunde inte stängas av.",
    disabledSuccess: "Registrering av sidvisningar har stängts av.",
  }],
]);

export function pageViewText(locale: SiteLocale, key: PageViewMessageKey): string {
  return PAGE_VIEW_MESSAGES.get(locale)?.[key] ?? PAGE_VIEW_MESSAGES.get("en")![key];
}

export function pageViewPrivacyDisclosure(locale: SiteLocale): string {
  return ["consent", "fields", "excluded", "retention", "session"]
    .map((key) => pageViewText(locale, key as PageViewMessageKey))
    .join(" ");
}
