// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Mirror the runtime precedence in src/lib/database-url.ts: the static
    // per-scope DEEPGLOT_DATABASE_URL (2-dataset topology, ROADMAP 8.6) wins;
    // plain DATABASE_URL stays as the self-host/local fallback (#59).
    url: process.env["DEEPGLOT_DATABASE_URL"]?.trim() || process.env["DATABASE_URL"],
  },
});
